name: AI Report Feedback

on:
  push:
    tags:
      - 'feedback-*'
      - 'review-*'

permissions:
  contents: read
  issues: write
  models: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Use a container for consistent environment
    container:
      image: python:3.11-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for context

      - name: Install dependencies
        run: |
          pip install pyyaml requests quarto quarto-cli Pillow

      - name: Render Quarto Report
        run: |
          # Render the report to generate figures from notebook cells.
          # We continue on error so that if the student's code fails,
          # the feedback process can still analyze the raw .qmd file.
          quarto render
        continue-on-error: true

      - name: Parse report
        id: parse
        run: python .github/scripts/parse_report.py
        continue-on-error: false

      - name: Generate AI feedback
        id: feedback
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: python .github/scripts/ai_feedback_criterion.py
        continue-on-error: false

      - name: Create feedback issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python .github/scripts/create_issue.py
        continue-on-error: false

      - name: Check debug upload setting
        id: check-debug-upload
        run: |
          # Check if debug_mode.upload_artifacts is enabled
          UPLOAD=$(python3 -c "
          import yaml
          try:
              with open('.github/feedback/config.yml') as f:
                  config = yaml.safe_load(f)
              upload = config.get('debug_mode', {}).get('upload_artifacts', False)
              print('true' if upload else 'false')
          except:
              print('false')
          ")
          echo "upload=$UPLOAD" >> $GITHUB_OUTPUT
          echo "Debug artifact upload: $UPLOAD"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: feedback-artifacts
          path: |
            parsed_report.json
            feedback.md
          retention-days: 30

      - name: Upload debug artifacts
        # Only upload if explicitly enabled in config AND debug directory exists
        # WARNING: Contains student work and grading prompts - use with caution!
        if: always() && steps.check-debug-upload.outputs.upload == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: feedback-debug-${{ github.run_number }}
          path: .github/debug/
          retention-days: 30
          if-no-files-found: ignore  # Don't fail if debug mode is disabled
